<footer class="bg-dark text-center text-white">
        <div class="text-center p-3 bg-dark fixed-bottom">
                © 2024 Copyright: <a class="text-white" href="https://cataas.com/cat">NEvangelista.com</a>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
